### ISSUE TITLE
Cannot Create a file when that file already exists

### ISSUE THREAD

**Issue by SillyLilyTransfem** [BlueberryWolf/WEBFISHINGModdingGuide#1]
My command prompt gives me this message when attempting to complete Part five of step 3.

**Comment by 6ZzwjdpNgL** [comment]
Did you create the folder in both projects? if so, delete the folder in the decompiled project, then run the command again.

**Comment by BlueberryWolf** [comment]
I'm not sure if you fixed the issue because you never replied. I'll close this, but if you need help again just open another issue
